easy_admin:
  site_name: 'Une année de voyages'
  entities:
    Article:
      class: App\Entity\Article
      label: 'Article'
      form:
        fields:
          - title
          - content
          - shortDescription
          - tags
          - articleCategory
    ArticleCategory:
      class: App\Entity\ArticleCategory
      label: 'Categorie Article'
  design:
    color_scheme: 'light'
    brand_color: 'rgba(26, 188, 156, 0.85)'